name: albert
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  go_router: ^17.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^4.12.1
  firebase_auth: ^6.5.4
  google_sign_in: ^7.2.0
  flutter_dotenv: ^6.0.1
  cloud_firestore: ^6.7.1
  firebase_storage: ^13.4.5
  firebase_ai: ^3.9.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  connectivity_plus: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo.png

